from snakemake.utils import min_version

min_version("7.25")


include: "rules/0.0_angsd_pipeline.smk"
include: "rules/0.1_intergenic_bed.smk"
include: "rules/2.0_landscape_modeling.smk"
include: "rules/4.0_permutation_tests.smk"


angsd

all_outputs = []

if config["downsample"]["fst"]:
    all_outputs.append("results/datasets/{dataset}/analyses/fst/downsampled/{dataset}.{ref}_poppairs.downsampled_{sites}-filts.fst.global.tsv")

if config["downsample"]["thetas"]:
    all_outputs.append("results/datasets/{dataset}/analyses/thetas/downsampled/{dataset}.{ref}_all.downsampled_{sites}-filts.thetaMean.{win}_{step}.tsv")



rule all:
    input:
        rules.angsd_all.input,
        expand(
            all_outputs,
            dataset=config["dataset"],
            ref=config["reference"]["name"],
            sites="allsites",
            win=config["params"]["thetas"]["win_size"],
            step=config["params"]["thetas"]["win_step"],
        ),
    default_target: True
